<h2><?= $this->page->name ?></h2>
<div>
  <h3>
    Components
  </h3>
  <div>
  <a href="<?= $this->url(array('controller' => 'component' , 'action' => 'new' , null , 'pageId' => $this->pageId),null,false) ?>">
    Create Component
  </a>

    |

  <a href="<?= $this->url(array('controller' => 'componet' , 'action' => 'add-to-page')) ?>">
    Add component to page
  </a>

</div>
</div>
<div>
  <h3>
    Tasks
  </h3>
  <a href="<?= $this->url(array('controller' => 'task' , 'action' => 'new' . null , 'pageId' => $this->pageId)) ?>">New Task</a>
</div>
<div>
  <h3>
    Issues
  </h3>
</div>