<h1><?= Lumiaproject_Translate::text('My Projects') ?></h1>
<a href="<?= $this->url(array('controller' => 'project', 'action' => 'new')) ?>" class="button">Add new project</a>

<div class="span-24" style="margin-top: 35px;">    
    <?php foreach ($this->projects as $project): ?>
        <div class="span-24">    

            <a href="<?= $this->url(array('controller' => 'project', 'action' => 'index', 'projectId' => $project->id_project)) ?>">
                <div class="span-6 box">
                    <?= $project->name; ?>
                </div>    
            </a>

        </div>  
    <?php endforeach; ?>
</div>